// Loaded after the pinned V4 app. No WebXR transport or pose math is replaced.
Object.assign(HG_DAGGER_MODE_LABELS, {
  DISARMED: 'Ready: Y starts inference and recording',
  POLICY_ACTIVE: 'Policy control: GL/GR takes over; A saves; X discards',
  FAILURE_HOLD: 'Stopping policy; waiting for robot hold',
  EXPERT_RELEASE_REQUIRED: 'Release both Grips, then re-grip to re-anchor',
  EXPERT_READY: 'Grip moves; A saves; X discards; B resets',
  EXPERT_ACTIVE: 'Human: A saves; X discards; B resets',
  ESTOP: 'Output stopped: inspect controller before restarting'
});

ensureHgControlsHud = function () {
  if (state.hgControlsHud) return state.hgControlsHud;
  const hud = createHgCanvasHud('hg-dagger-controls-hud', 144, 0.37);
  if (!hud) return null;
  drawHgPanelBackground(hud, 0.48);
  hud.context.fillStyle = '#F0F4F8';
  hud.context.font = '500 30px sans-serif';
  hud.context.fillText('Y: Start   GL/GR: Take over   A: Save   X: Discard', 32, 47);
  hud.context.fillText('Keep Grip held to move after hold. B: Discard + reset', 32, 99);
  hud.texture.needsUpdate = true;
  state.hgControlsHud = hud;
  return hud;
};

hgDaggerVisualState = function (status) {
  const invalid = status?.trial?.invalid_reason;
  const notice = status?.notice;
  const mode = String(status?.mode || 'DISARMED');
  return {
    key: String(invalid || notice?.token || mode),
    label: invalid ? `Episode INVALID: ${invalid}. B discards and resets.`
      : notice?.text || HG_DAGGER_MODE_LABELS[mode] || mode,
    color: invalid || notice?.level === 'error' ? '#FF6B6B' : '#7DFFCF',
    notice: Boolean(invalid || notice?.text)
  };
};

const collectorOriginalHud = updateHgStatusHud;
updateHgStatusHud = function (status, options) {
  // Remove legacy button instructions from notices generated by the base app.
  if (status) status.prompt = HG_DAGGER_MODE_LABELS[status.mode] || status.mode;
  collectorOriginalHud(status, options);
  // Feedback now has one owner. Prevent the base app from also generating a
  // generic transition pulse on top of the receipt-specific rhythm.
  state.teleop.lastHgDaggerMode = status?.mode || null;
  state.teleop.lastHgDaggerHapticToken = status?.haptic_token ?? null;
};

// Also identify pages served by a web process started before the new index.
const collectorGuide = document.querySelector('.dagger-guide');
if (document.title !== 'CB Collector | DAgger 300') {
  document.title = 'CB Collector | DAgger 300';
  const title = document.querySelector('.title');
  if (title) title.textContent = document.title;
  if (collectorGuide) collectorGuide.textContent =
    'Y: start inference + recording. GL/GR: human takeover. A: save. '
    + 'X: discard. B: discard unsaved episode + reset. '
    + 'Keep Grip held through the hold transition. No A long-press action.';
}
const collectorHint = document.querySelector('.hardware-safety-hint');
if (collectorHint) collectorHint.textContent = 'B resets all body joints and grippers. Keep the robot workspace clear.';
setHardwareButtonText = function (button) {
  if (button) button.textContent = hardwareControlIsOnOrBusy()
    ? 'Stop session (discard unsaved episode)' : 'Hold to start inference + recording';
};
