// Loaded after the pinned V4 app. No WebXR transport or pose math is replaced.
Object.assign(HG_DAGGER_MODE_LABELS, {
  DISARMED: '待命：A 开始推理和录制',
  POLICY_ACTIVE: '模型控制：握持键接管；B 保存；Y 丢弃',
  FAILURE_HOLD: '模型已停止，等待控制器保持',
  EXPERT_RELEASE_REQUIRED: '松开握持键，再握重新锚定',
  EXPERT_READY: '握持移动；B 保存；Y 丢弃；X 复位',
  EXPERT_ACTIVE: '人工纠错：B 保存；Y 丢弃；X 复位',
  ESTOP: '输出已停止，请先检查错误'
});

ensureHgControlsHud = function () {
  if (state.hgControlsHud) return state.hgControlsHud;
  const hud = createHgCanvasHud('hg-dagger-controls-hud', 144, 0.37);
  if (!hud) return null;
  drawHgPanelBackground(hud, 0.48);
  hud.context.fillStyle = '#F0F4F8';
  hud.context.font = '500 30px sans-serif';
  hud.context.fillText('A 开始 · 握持接管 · B 保存 · Y 丢弃', 32, 47);
  hud.context.fillText('X 仅复位（先保存或丢弃） · B/Y 不复位', 32, 99);
  hud.texture.needsUpdate = true;
  state.hgControlsHud = hud;
  return hud;
};

hgDaggerVisualState = function (status) {
  const invalid = status?.trial?.invalid_reason;
  const notice = status?.notice;
  const mode = String(status?.mode || 'DISARMED');
  return {
    key: String(invalid || notice?.token || mode),
    label: invalid ? `本条失效：${invalid}；Y 丢弃，X 仅全身复位（先保存或丢弃当前条）。`
      : notice?.text || HG_DAGGER_MODE_LABELS[mode] || mode,
    color: invalid || notice?.level === 'error' ? '#FF6B6B' : '#7DFFCF',
    notice: Boolean(invalid || notice?.text)
  };
};

const collectorOriginalHud = updateHgStatusHud;
updateHgStatusHud = function (status, options) {
  // Remove legacy button instructions from notices generated by the base app.
  if (status) status.prompt = HG_DAGGER_MODE_LABELS[status.mode] || status.mode;
  collectorOriginalHud(status, options);
  // Feedback now has one owner. Prevent the base app from also generating a
  // generic transition pulse on top of the receipt-specific rhythm.
  state.teleop.lastHgDaggerMode = status?.mode || null;
  state.teleop.lastHgDaggerHapticToken = status?.haptic_token ?? null;
};

// Also identify pages served by a web process started before the new index.
const collectorGuide = document.querySelector('.dagger-guide');
if (document.title !== 'CB Collector | DAgger 300') {
  document.title = 'CB Collector | DAgger 300';
  const title = document.querySelector('.title');
  if (title) title.textContent = document.title;
  if (collectorGuide) collectorGuide.textContent =
    'A 开始推理和录制；握持接管；B 保存；'
    + 'Y 丢弃；X 仅全身复位（先保存或丢弃当前条）；'
    + '短按面键操作，长按不重复。Y 不负责退出，退出用启动器或终端 Q。';
}
const collectorHint = document.querySelector('.hardware-safety-hint');
if (collectorHint) collectorHint.textContent = 'B/Y 不复位；X 仅全身复位（先保存或丢弃当前条）。';
setHardwareButtonText = function (button) {
  if (button) button.textContent = hardwareControlIsOnOrBusy()
    ? '停止会话（丢弃未保存本条）' : '长按进入 VR（待命；A 开始）';
};

/* Entering/reconnecting VR never starts a trial, including older reviewed UIs. */
maybeEnableAfterFreshVr = async function () {
  cancelDeferredHardwareEnable('VR 待命，按 A 或启动器开始按钮。');
};
finishHardwareEnableHold = function (event) {
  const confirmed = state.teleop.holdTriggered;
  state.teleop.holdTriggered = false;
  cancelHardwareEnableHold();
  if (!confirmed) return;
  if (event) event.preventDefault();
  cancelDeferredHardwareEnable('VR 待命，按 A 开始推理和录制。');
  setStatus('进入 VR 后保持待命；按 A 开始。');
  void enterVr();
};
